version: '3.4'

services:
  postgres:
    build: backend/postgres-dev/
    container_name: postgres
    ports:
    - 5432:5432
    restart: always
    volumes:
    - ./backend/db_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
   
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  assesment:
    container_name: project
    build: backend/assesment
    command: sh ./docker-entrypoint.sh
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - postgres
    #volumes:
    #  - ./backend/devkeys:/tmp/secrets
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: imroz
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: projectdb
      MONGO_ATLAS_CONNECTION_STRING: None
